- hosts: WebServer
  remote_user: root
  tasks:
  - name: install tomcat8
    become: yes
    apt:
     name: tomcat8
     state: present

  - name: copying to home path
    copy:
     src: /var/lib/jenkins/workspace/terraform_sample/SpringMVCSecurityXML/target/SpringMVCSecurityXML.war
     dest: ~/


  - name: create backup
    file:
     path: ~/backup
     state: directory

  - name: run script to copy current version to previous and latest to current
    script: ./backup.sh

  - name: deleting from home path
    file:
     path: ~/SpringMVCSecurityXML.war
     state: absent

  - name: deploy java app
    become: yes
    copy:
      src: /var/lib/jenkins/workspace/terraform_sample/SpringMVCSecurityXML/target/SpringMVCSecurityXML.war
      dest: /var/lib/tomcat8/webapps
